language: java
sudo: false
os:
    - linux
dist: trusty
jdk:
    - openjdk8
cache:
    directories:
        - $HOME/.m2

install:
script:
    - cd back-end && ./mvnw package -B -DskipTests=true && cd ..
